# Generated by Django 5.1.1 on 2024-11-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_delete_estadoticket_alter_rol_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
