# Generated by Django 5.1.2 on 2024-11-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='hora_ingreso',
            field=models.TimeField(),
        ),
    ]
