# Generated by Django 5.1.3 on 2024-11-25 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_alter_tickete_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickete',
            name='price',
            field=models.FloatField(blank=True, default='20.0', null=True),
        ),
        migrations.CreateModel(
            name='TicketS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('entrace_time', models.TimeField(blank=True, null=True)),
                ('exit_time', models.TimeField(blank=True, null=True)),
                ('patente', models.CharField(max_length=6)),
                ('price', models.FloatField(blank=True, default='20.0', null=True)),
                ('min_lapsed', models.PositiveIntegerField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('state', models.ForeignKey(default=3, on_delete=django.db.models.deletion.RESTRICT, to='tickets.ticketstate')),
            ],
        ),
    ]
