# Generated by Django 5.1.3 on 2024-11-26 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_alter_tickete_patente_alter_tickets_patente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketE',
            new_name='TicketEntrada',
        ),
        migrations.RenameModel(
            old_name='TicketS',
            new_name='TicketSalida',
        ),
    ]
