# Generated by Django 5.1.3 on 2024-11-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_rename_tickete_ticketentrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsalida',
            name='min_lapsed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
