# Generated by Django 5.1.3 on 2024-12-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_alter_rol_name_alter_ticketstate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='number',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
