# Generated by Django 5.1.3 on 2024-12-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_alter_protocolo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='number',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='rut',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
