# Generated by Django 5.1.3 on 2024-12-17 01:26

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_alter_protocolo_number_alter_protocolo_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+56', max_length=128, null=True, region='CL'),
        ),
    ]
