# Generated by Django 5.1.3 on 2024-12-17 01:42

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_alter_protocolo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='CL'),
        ),
    ]
