# Generated by Django 5.1.1 on 2024-11-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_usuario_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoTicket',
        ),
        migrations.AlterField(
            model_name='rol',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
