# Generated by Django 5.1.3 on 2024-11-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_alter_tickete_price_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickete',
            name='patente',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='patente',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
