# Generated by Django 5.1.1 on 2024-11-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_alter_ticketsalida_min_lapsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsalida',
            name='min_lapsed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
