# Generated by Django 5.1.3 on 2024-11-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_alter_ticketsalida_min_lapsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketstate',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
