# Generated by Django 5.1.1 on 2024-12-18 07:09

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_alter_rol_name_alter_ticketstate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='CL'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='rut',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
