# Generated by Django 5.1.2 on 2024-11-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=9)),
                ('patente', models.CharField(max_length=6)),
                ('hora_ingreso', models.CharField(max_length=4)),
                ('hora_salida', models.CharField(max_length=4)),
                ('date', models.CharField(max_length=8)),
                ('description', models.TextField(max_length=45, verbose_name='Descripción')),
            ],
        ),
    ]
