# Generated by Django 5.1.2 on 2024-11-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_protocolo_hora_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='hora_salida',
            field=models.TimeField(),
        ),
    ]
