# Generated by Django 5.1.2 on 2024-11-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_alter_protocolo_date_alter_protocolo_hora_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='last_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
