# Generated by Django 5.1.3 on 2024-11-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_alter_protocolo_last_name_alter_protocolo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entrace_time', models.TimeField()),
                ('patente', models.CharField(max_length=6)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='description',
            field=models.TextField(max_length=45),
        ),
    ]
