# Generated by Django 5.1.3 on 2024-11-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_tickete_alter_protocolo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickete',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickete',
            name='entrace_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickete',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
