# Generated by Django 5.1.1 on 2024-11-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_alter_tickete_date_alter_tickete_entrace_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
