# Generated by Django 5.1.1 on 2024-11-20 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_ticketstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickete',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='tickets.ticketstate'),
            preserve_default=False,
        ),
    ]
