# Generated by Django 5.1.1 on 2024-11-20 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_tickete_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickete',
            name='state',
        ),
    ]
