# Generated by Django 5.1.3 on 2024-11-21 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_tickete_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickete',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='tickets.ticketstate'),
        ),
    ]
